/**
 * Lista oficial completa de todos os 185 municípios do Estado de Pernambuco (PE)
 * (184 municípios autônomos + 1 distrito estadual Fernando de Noronha).
 * Fonte de referência: IBGE / Governo do Estado de Pernambuco.
 */

export const PERNAMBUCO_CITIES = [
  'Abreu e Lima',
  'Afogados da Ingazeira',
  'Afrânio',
  'Agrestina',
  'Água Preta',
  'Águas Belas',
  'Alagoinha',
  'Aliança',
  'Altinho',
  'Amaraji',
  'Angelim',
  'Araçoiaba',
  'Araripina',
  'Arcoverde',
  'Barra de Guabiraba',
  'Barreiros',
  'Belém de Maria',
  'Belém do São Francisco',
  'Belo Jardim',
  'Betânia',
  'Bezerros',
  'Bodocó',
  'Bom Conselho',
  'Bom Jardim',
  'Bonito',
  'Brejão',
  'Brejinho',
  'Brejo da Madre de Deus',
  'Buenos Aires',
  'Buíque',
  'Cabo de Santo Agostinho',
  'Cabrobó',
  'Cachoeirinha',
  'Caetés',
  'Calçado',
  'Calumbi',
  'Camaragibe',
  'Camocim de São Félix',
  'Camutanga',
  'Canhotinho',
  'Capoeiras',
  'Carnaíba',
  'Carnaubeira da Penha',
  'Carpina',
  'Caruaru',
  'Casinhas',
  'Catende',
  'Cedro',
  'Chã de Alegria',
  'Chã Grande',
  'Condado',
  'Correntes',
  'Cortês',
  'Cumaru',
  'Cupira',
  'Custódia',
  'Dormentes',
  'Escada',
  'Exu',
  'Feira Nova',
  'Fernando de Noronha',
  'Ferreiros',
  'Flores',
  'Floresta',
  'Frei Miguelinho',
  'Gameleira',
  'Garanhuns',
  'Glória do Goitá',
  'Goiana',
  'Granito',
  'Gravatá',
  'Iati',
  'Ibimirim',
  'Ibirajuba',
  'Igarassu',
  'Iguaracy',
  'Ilha de Itamaracá',
  'Inajá',
  'Ingazeira',
  'Ipojuca',
  'Ipubi',
  'Itacuruba',
  'Itaíba',
  'Itambé',
  'Itapetim',
  'Itapissuma',
  'Itaquitinga',
  'Jaboatão dos Guararapes',
  'Jaqueira',
  'Jataúba',
  'Jatobá',
  'João Alfredo',
  'Joaquim Nabuco',
  'Jucati',
  'Jupi',
  'Jurema',
  'Lagoa de Itaenga',
  'Lagoa do Carro',
  'Lagoa do Ouro',
  'Lagoa dos Gatos',
  'Lagoa Grande',
  'Lajedo',
  'Limoeiro',
  'Macaparana',
  'Machados',
  'Manari',
  'Maraial',
  'Mirandiba',
  'Moreilândia',
  'Moreno',
  'Nazaré da Mata',
  'Olinda',
  'Orobó',
  'Orocó',
  'Ouricuri',
  'Palmares',
  'Palmeirina',
  'Panelas',
  'Paranatama',
  'Parnamirim',
  'Passira',
  'Paudalho',
  'Paulista',
  'Pedra',
  'Pesqueira',
  'Petrolândia',
  'Petrolina',
  'Poção',
  'Pombos',
  'Primavera',
  'Quipapá',
  'Quixaba',
  'Recife',
  'Riacho das Almas',
  'Ribeirão',
  'Rio Formoso',
  'Sairé',
  'Salgadinho',
  'Salgueiro',
  'Saloá',
  'Sanharó',
  'Santa Cruz',
  'Santa Cruz da Baixa Verde',
  'Santa Cruz do Capibaribe',
  'Santa Filomena',
  'Santa Maria da Boa Vista',
  'Santa Maria do Cambucá',
  'Santa Terezinha',
  'São Benedito do Sul',
  'São Bento do Una',
  'São Caitano',
  'São João',
  'São Joaquim do Monte',
  'São José da Coroa Grande',
  'São José do Belmonte',
  'São José do Egito',
  'São Lourenço da Mata',
  'São Vicente Férrer',
  'Serra Talhada',
  'Serrita',
  'Sertânia',
  'Sirinhaém',
  'Solidão',
  'Surubim',
  'Tabira',
  'Tacaimbó',
  'Tacaratu',
  'Tamandaré',
  'Taquaritinga do Norte',
  'Terezinha',
  'Terra Nova',
  'Timbaúba',
  'Toritama',
  'Tracunhaém',
  'Trindade',
  'Triunfo',
  'Tupanatinga',
  'Tuparetama',
  'Venturosa',
  'Verdejante',
  'Vertente do Lério',
  'Vertentes',
  'Vicência',
  'Vitória de Santo Antão',
  'Xexéu',
] as const;

export type PernambucoCity = (typeof PERNAMBUCO_CITIES)[number];

/**
 * Remove acentos e normaliza para caixa baixa para buscas insensíveis a caracteres especiais.
 */
export function normalizeSearchTerm(str: string): string {
  return (str || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

/**
 * Valida se uma string corresponde a um município oficial de Pernambuco (com ou sem acentos).
 */
export function isValidPernambucoCity(cityName: string): boolean {
  if (!cityName || typeof cityName !== 'string') return false;
  const normalized = normalizeSearchTerm(cityName);
  return PERNAMBUCO_CITIES.some((city) => normalizeSearchTerm(city) === normalized);
}

/**
 * Retorna o nome oficial formatado com acentos corretos a partir de um termo de busca.
 */
export function getCanonicalPernambucoCity(cityName: string): string | null {
  if (!cityName) return null;
  const normalized = normalizeSearchTerm(cityName);
  const found = PERNAMBUCO_CITIES.find((city) => normalizeSearchTerm(city) === normalized);
  return found || null;
}
