import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'crypto';
import { verifyMercadoPagoWebhookSignature } from '../signature.ts';
import { webhookPayloadSchema } from '../schemas.ts';

describe('Mercado Pago Webhook Processing & Security', () => {
  const secret = 'webhook_secret_998877';

  it('rejects webhooks with missing x-signature', () => {
    const isValid = verifyMercadoPagoWebhookSignature({
      xSignature: null,
      xRequestId: 'req-123',
      dataId: '123456',
      secret,
    });
    assert.equal(isValid, false);
  });

  it('validates legitimate webhook headers generated by Mercado Pago algorithm', () => {
    const dataId = '555666777';
    const xRequestId = 'test-uuid-req';
    const ts = String(Math.floor(Date.now() / 1000));

    const manifest = `id:${dataId};request-id:${xRequestId};ts:${ts};`;
    const hash = crypto.createHmac('sha256', secret).update(manifest).digest('hex');

    const xSignature = `ts=${ts},v1=${hash}`;

    const isValid = verifyMercadoPagoWebhookSignature({
      xSignature,
      xRequestId,
      dataId,
      secret,
    });

    assert.equal(isValid, true);
  });

  it('correctly parses webhook event payload structure', () => {
    const rawPayload = {
      action: 'payment.created',
      api_version: 'v1',
      data: { id: '999888' },
      date_created: '2026-09-12T12:00:00Z',
      id: 112233,
      live_mode: false,
      type: 'payment',
      user_id: 12345,
    };

    const parsed = webhookPayloadSchema.safeParse(rawPayload);
    assert.equal(parsed.success, true);
    if (parsed.success) {
      assert.equal(parsed.data.type, 'payment');
      assert.equal(parsed.data.data?.id, '999888');
    }
  });
});
